//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibrahimekinci.Plugin.Localization.Public {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YazilimMuhendisligiProje.ibrahimekinci.Plugin.Localization.Public.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GeneralLogIn {
            get {
                return ResourceManager.GetString("GeneralLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapmak için tıklayınız.
        /// </summary>
        public static string GeneralLoginClick {
            get {
                return ResourceManager.GetString("GeneralLoginClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string GeneralLogoff {
            get {
                return ResourceManager.GetString("GeneralLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazarlama.
        /// </summary>
        public static string GeneralMarketing {
            get {
                return ResourceManager.GetString("GeneralMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni.
        /// </summary>
        public static string GeneralNew {
            get {
                return ResourceManager.GetString("GeneralNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string GeneralRegister {
            get {
                return ResourceManager.GetString("GeneralRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string GeneralSelect {
            get {
                return ResourceManager.GetString("GeneralSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string GeneralSite {
            get {
                return ResourceManager.GetString("GeneralSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik.
        /// </summary>
        public static string LabelActivity {
            get {
                return ResourceManager.GetString("LabelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Detay.
        /// </summary>
        public static string LabelAddressDetail {
            get {
                return ResourceManager.GetString("LabelAddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresler.
        /// </summary>
        public static string LabelAddresses {
            get {
                return ResourceManager.GetString("LabelAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres ad.
        /// </summary>
        public static string LabelAddressName {
            get {
                return ResourceManager.GetString("LabelAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        public static string LabelAdmin {
            get {
                return ResourceManager.GetString("LabelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru.
        /// </summary>
        public static string LabelAnnouncement {
            get {
                return ResourceManager.GetString("LabelAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string LabelArea {
            get {
                return ResourceManager.GetString("LabelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çanta.
        /// </summary>
        public static string LabelBag {
            get {
                return ResourceManager.GetString("LabelBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkili Kodu.
        /// </summary>
        public static string LabelBinaryCode {
            get {
                return ResourceManager.GetString("LabelBinaryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Günü.
        /// </summary>
        public static string LabelBirthday {
            get {
                return ResourceManager.GetString("LabelBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gövde.
        /// </summary>
        public static string LabelBody {
            get {
                return ResourceManager.GetString("LabelBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube.
        /// </summary>
        public static string LabelBranch {
            get {
                return ResourceManager.GetString("LabelBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Ad.
        /// </summary>
        public static string LabelBranchName {
            get {
                return ResourceManager.GetString("LabelBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehirler.
        /// </summary>
        public static string LabelCities {
            get {
                return ResourceManager.GetString("LabelCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum.
        /// </summary>
        public static string LabelComment {
            get {
                return ResourceManager.GetString("LabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Sayısı.
        /// </summary>
        public static string LabelCommentCount {
            get {
                return ResourceManager.GetString("LabelCommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string LabelConfirmPassword {
            get {
                return ResourceManager.GetString("LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçeler.
        /// </summary>
        public static string LabelCounties {
            get {
                return ResourceManager.GetString("LabelCounties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkeler.
        /// </summary>
        public static string LabelCountries {
            get {
                return ResourceManager.GetString("LabelCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string LabelCounty {
            get {
                return ResourceManager.GetString("LabelCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma tarihi.
        /// </summary>
        public static string LabelCreateDate {
            get {
                return ResourceManager.GetString("LabelCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string LabelDetail {
            get {
                return ResourceManager.GetString("LabelDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string LabelEndDate {
            get {
                return ResourceManager.GetString("LabelEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string LabelExtra {
            get {
                return ResourceManager.GetString("LabelExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string LabelForm {
            get {
                return ResourceManager.GetString("LabelForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string LabelGender {
            get {
                return ResourceManager.GetString("LabelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misafir.
        /// </summary>
        public static string LabelGuest {
            get {
                return ResourceManager.GetString("LabelGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik.
        /// </summary>
        public static string LabelHeight {
            get {
                return ResourceManager.GetString("LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon html.
        /// </summary>
        public static string LabelIconHtml {
            get {
                return ResourceManager.GetString("LabelIconHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmage url.
        /// </summary>
        public static string LabelImageUrl {
            get {
                return ResourceManager.GetString("LabelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string LabelIp {
            get {
                return ResourceManager.GetString("LabelIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğe.
        /// </summary>
        public static string LabelItem {
            get {
                return ResourceManager.GetString("LabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğeler.
        /// </summary>
        public static string LabelItems {
            get {
                return ResourceManager.GetString("LabelItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar.
        /// </summary>
        public static string LabelKey {
            get {
                return ResourceManager.GetString("LabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar Kelime.
        /// </summary>
        public static string LabelKeyword {
            get {
                return ResourceManager.GetString("LabelKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dil ailesi.
        /// </summary>
        public static string LabelLanguageCulture {
            get {
                return ResourceManager.GetString("LabelLanguageCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dil dosyası.
        /// </summary>
        public static string LabelLanguageResource {
            get {
                return ResourceManager.GetString("LabelLanguageResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı.
        /// </summary>
        public static string LabelLink {
            get {
                return ResourceManager.GetString("LabelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Dosyası.
        /// </summary>
        public static string LabelLocalizationResource {
            get {
                return ResourceManager.GetString("LabelLocalizationResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum.
        /// </summary>
        public static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medya.
        /// </summary>
        public static string LabelMedia {
            get {
                return ResourceManager.GetString("LabelMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Çantası.
        /// </summary>
        public static string LabelMediaBag {
            get {
                return ResourceManager.GetString("LabelMediaBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Türü.
        /// </summary>
        public static string LabelMediaType {
            get {
                return ResourceManager.GetString("LabelMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string LabelMenu {
            get {
                return ResourceManager.GetString("LabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Elaman.
        /// </summary>
        public static string LabelMenuItem {
            get {
                return ResourceManager.GetString("LabelMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to head açıklama.
        /// </summary>
        public static string LabelMetaDescription {
            get {
                return ResourceManager.GetString("LabelMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to head anahtar kelime.
        /// </summary>
        public static string LabelMetaKeywords {
            get {
                return ResourceManager.GetString("LabelMetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seo için gerekli olan başlık.
        /// </summary>
        public static string LabelMetaTitle {
            get {
                return ResourceManager.GetString("LabelMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştirilme Tarihi.
        /// </summary>
        public static string LabelModifedDate {
            get {
                return ResourceManager.GetString("LabelModifedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahalle.
        /// </summary>
        public static string LabelNeighborhood {
            get {
                return ResourceManager.GetString("LabelNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string LabelNewPassword {
            get {
                return ResourceManager.GetString("LabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim.
        /// </summary>
        public static string LabelNotification {
            get {
                return ResourceManager.GetString("LabelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Şifre.
        /// </summary>
        public static string LabelOldPassword {
            get {
                return ResourceManager.GetString("LabelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenek.
        /// </summary>
        public static string LabelOption {
            get {
                return ResourceManager.GetString("LabelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahip.
        /// </summary>
        public static string LabelOwner {
            get {
                return ResourceManager.GetString("LabelOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahip Türü.
        /// </summary>
        public static string LabelOwnerType {
            get {
                return ResourceManager.GetString("LabelOwnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Kodu.
        /// </summary>
        public static string LabelPhoneCode {
            get {
                return ResourceManager.GetString("LabelPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaka Kodu.
        /// </summary>
        public static string LabelPlateNo {
            get {
                return ResourceManager.GetString("LabelPlateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderi.
        /// </summary>
        public static string LabelPost {
            get {
                return ResourceManager.GetString("LabelPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post tip.
        /// </summary>
        public static string LabelPostType {
            get {
                return ResourceManager.GetString("LabelPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string LabelProduct {
            get {
                return ResourceManager.GetString("LabelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herkese Açık Ad.
        /// </summary>
        public static string LabelPublicName {
            get {
                return ResourceManager.GetString("LabelPublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru.
        /// </summary>
        public static string LabelQuestion {
            get {
                return ResourceManager.GetString("LabelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota.
        /// </summary>
        public static string LabelQuota {
            get {
                return ResourceManager.GetString("LabelQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okunma zamanı.
        /// </summary>
        public static string LabelReadingDate {
            get {
                return ResourceManager.GetString("LabelReadingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu browserda beni tanı.
        /// </summary>
        public static string LabelRememberBrowser {
            get {
                return ResourceManager.GetString("LabelRememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string LabelRememberMe {
            get {
                return ResourceManager.GetString("LabelRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sira.
        /// </summary>
        public static string LabelRow {
            get {
                return ResourceManager.GetString("LabelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısa Detay.
        /// </summary>
        public static string LabelShortDetail {
            get {
                return ResourceManager.GetString("LabelShortDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url.
        /// </summary>
        public static string LabelSiteUrl {
            get {
                return ResourceManager.GetString("LabelSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string LabelStartDate {
            get {
                return ResourceManager.GetString("LabelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görünürlük.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Görünürlüğü.
        /// </summary>
        public static string LabelStatusComment {
            get {
                return ResourceManager.GetString("LabelStatusComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        public static string LabelStock {
            get {
                return ResourceManager.GetString("LabelStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string LabelSubject {
            get {
                return ResourceManager.GetString("LabelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone.
        /// </summary>
        public static string LabelSubscriber {
            get {
                return ResourceManager.GetString("LabelSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sayfa tag.
        /// </summary>
        public static string LabelTags {
            get {
                return ResourceManager.GetString("LabelTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süre.
        /// </summary>
        public static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üçlü Kodu.
        /// </summary>
        public static string LabelTripleCode {
            get {
                return ResourceManager.GetString("LabelTripleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string LabelUser {
            get {
                return ResourceManager.GetString("LabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görünürlük.
        /// </summary>
        public static string LabelVisible {
            get {
                return ResourceManager.GetString("LabelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genişlik.
        /// </summary>
        public static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip code.
        /// </summary>
        public static string LabelZipCode {
            get {
                return ResourceManager.GetString("LabelZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletişim Formu.
        /// </summary>
        public static string MenuContactForm {
            get {
                return ResourceManager.GetString("MenuContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır Mesaj.
        /// </summary>
        public static string MenuMessageTemplate {
            get {
                return ResourceManager.GetString("MenuMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ayarları.
        /// </summary>
        public static string MenuSiteSetings {
            get {
                return ResourceManager.GetString("MenuSiteSetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        public static string MenuSupport {
            get {
                return ResourceManager.GetString("MenuSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postanızı teyit ettiğiniz için teşekkür ederiz. Lütfen.
        /// </summary>
        public static string MessageConfirmedEmail {
            get {
                return ResourceManager.GetString("MessageConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Onayla.
        /// </summary>
        public static string MessageConfirmEmail {
            get {
                return ResourceManager.GetString("MessageConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen hesabınızı onaylamak için tıklayın.
        /// </summary>
        public static string MessageConfirmYourAccountContent {
            get {
                return ResourceManager.GetString("MessageConfirmYourAccountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabını onayla.
        /// </summary>
        public static string MessageConfirmYourAccountSubject {
            get {
                return ResourceManager.GetString("MessageConfirmYourAccountSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string MessageHello {
            get {
                return ResourceManager.GetString("MessageHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına girilen değer  {1}  alanıyla aynı olmalıdır..
        /// </summary>
        public static string Warning_Compare {
            get {
                return ResourceManager.GetString("Warning_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Warning_Error {
            get {
                return ResourceManager.GetString("Warning_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı girilmesi zorunludur..
        /// </summary>
        public static string Warning_FieldRequired {
            get {
                return ResourceManager.GetString("Warning_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  alanına en az {2} en çok {1} karakter girilebilir..
        /// </summary>
        public static string Warning_Interval {
            get {
                return ResourceManager.GetString("Warning_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Kod.
        /// </summary>
        public static string Warning_InvalidCode {
            get {
                return ResourceManager.GetString("Warning_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz giriş.
        /// </summary>
        public static string Warning_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Warning_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı {1} karakter olmalıdır..
        /// </summary>
        public static string Warning_LenghtLimit {
            get {
                return ResourceManager.GetString("Warning_LenghtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilitlenme.
        /// </summary>
        public static string Warning_Lockout {
            get {
                return ResourceManager.GetString("Warning_Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı en fazla {1} karakter olmalıdır..
        /// </summary>
        public static string Warning_MaxLenght {
            get {
                return ResourceManager.GetString("Warning_MaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı en az {1} karakter olmalıdır..
        /// </summary>
        public static string Warning_MinLenght {
            get {
                return ResourceManager.GetString("Warning_MinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına hatalı tipde veri girildi!.
        /// </summary>
        public static string Warning_Type {
            get {
                return ResourceManager.GetString("Warning_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta Onayla.
        /// </summary>
        public static string WarningConfirmEmail {
            get {
                return ResourceManager.GetString("WarningConfirmEmail", resourceCulture);
            }
        }
    }
}
